# Generated by Django 6.0.7 on 2026-07-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("picture", models.CharField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("derivation", models.TextField(blank=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("Relationships", "relationships"),
                            ("Success", "success"),
                            ("Lust", "lust"),
                            ("God", "god"),
                            ("Progress", "progress"),
                            ("Comfort", "comfort"),
                            ("Money", "money"),
                            ("Death", "death"),
                            ("Truth", "truth"),
                            ("Joy", "joy"),
                            ("Society", "society"),
                            ("Politics", "politics"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="quotes.author",
                    ),
                ),
            ],
        ),
    ]
