# Generated by Django 6.0.7 on 2026-07-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_quote_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
